name: planmorph
region: nyc

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /api
    - component:
        name: admin
      match:
        path:
          prefix: /admin
    - component:
        name: client
      match:
        path:
          prefix: /

services:
  - name: api
    github:
      repo: PlanMorph-Org/planmorph
      branch: main
      deploy_on_push: true
    source_dir: .
    dockerfile_path: PlanMorph.Api/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: ConnectionStrings__DefaultConnection
        scope: RUN_TIME
        value: Host=planmorph-do-user-30645514-0.h.db.ondigitalocean.com;Port=25060;Database=planmorphdb;Username=doadmin;Password=AVNS_ks1_9lUcdQw3jqD3bL8;SSL Mode=Require;Trust Server Certificate=true
      - key: JwtSettings__Secret
        scope: RUN_TIME
        value: PlanMorph_JWT_Prod_2026_SuperSecretKey_ChangeMe123!
      - key: JwtSettings__Issuer
        value: PlanMorph
      - key: JwtSettings__Audience
        value: PlanMorph
      - key: JwtSettings__ExpiryMinutes
        value: "60"
      - key: EmailSettings__SmtpHost
        scope: RUN_TIME
        value: smtp.gmail.com
      - key: EmailSettings__SmtpPort
        scope: RUN_TIME
        value: "587"
      - key: EmailSettings__SmtpUsername
        scope: RUN_TIME
        value: lawravasco@gmail.com
      - key: EmailSettings__SmtpPassword
        scope: RUN_TIME
        value: iyst dhcl wepo uitp
      - key: EmailSettings__FromEmail
        scope: RUN_TIME
        value: noreply@planmorph.com
      - key: EmailSettings__FromName
        value: PlanMorph
      - key: Currency__Base
        scope: RUN_TIME
        value: KES
      - key: Currency__ProviderUrl
        scope: RUN_TIME
        value: https://api.exchangerate.host/latest?base={BASE}
      - key: Currency__CacheMinutes
        scope: RUN_TIME
        value: "720"
      - key: Paystack__BaseUrl
        scope: RUN_TIME
        value: https://api.paystack.co
      - key: Paystack__SecretKey
        scope: RUN_TIME
        value: sk_live_a1682f30dcaebe86c73819607c241a176ac7d12d
      - key: Paystack__WebhookSecret
        scope: RUN_TIME
        value: thisisplanmorphspaymentsystemcominginthroughpaystackbutusingtalosysasthecompanyuntilregistrationcanbecompleted
      - key: Paystack__CallbackUrl
        scope: RUN_TIME
        value: https://planmorph-i8sge.ondigitalocean.app/payment/callback
      - key: Paystack__Currency
        scope: RUN_TIME
        value: KES
      - key: DigitalOcean__SpacesAccessKey
        scope: RUN_TIME
        value: DO801HR4Q8VLDVZZ7VJJ
      - key: DigitalOcean__SpacesSecretKey
        scope: RUN_TIME
        value: 0izQLJdg7EvVzJ/U1YKymltRA6V63cHR73LJUdP3n5M
      - key: DigitalOcean__BucketName
        scope: RUN_TIME
        value: planmorph
      - key: DigitalOcean__Region
        scope: RUN_TIME
        value: fra1
      - key: DigitalOcean__SpacesEndpoint
        scope: RUN_TIME
        value: https://fra1.digitaloceanspaces.com
      - key: Cors__AllowedOrigins__0
        scope: RUN_TIME
        value: https://planmorph-i8sge.ondigitalocean.app
      - key: Cors__AllowedOrigins__1
        scope: RUN_TIME
        value: http://localhost:3000
      - key: Cors__AllowedOrigins__2
        scope: RUN_TIME
        value: http://localhost:5059
    health_check:
      http_path: /health
      port: 80

  - name: client
    github:
      repo: PlanMorph-Org/planmorph
      branch: main
      deploy_on_push: true
    source_dir: planmorph-client
    dockerfile_path: planmorph-client/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: /api/api
    health_check:
      http_path: /
      port: 3000

  - name: admin
    github:
      repo: PlanMorph-Org/planmorph
      branch: main
      deploy_on_push: true
    source_dir: .
    dockerfile_path: PlanMorph.Admin/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: ConnectionStrings__DefaultConnection
        scope: RUN_TIME
        value: Host=planmorph-do-user-30645514-0.h.db.ondigitalocean.com;Port=25060;Database=planmorphdb;Username=doadmin;Password=AVNS_ks1_9lUcdQw3jqD3bL8;SSL Mode=Require;Trust Server Certificate=true
      - key: ApiBaseUrl
        scope: RUN_TIME
        value: http://api:80
    health_check:
      http_path: /
      port: 80
